### ISSUE TITLE
Problem with compiling

### ISSUE THREAD

**Issue by Russel88** [arumugamlab/msamtools#1]
Hi

I get the following error when I run `make`:
```sh
libmaui.a(msam_filter.o): In function `mFilterFileWrapper':
.../Software/msamtools-0.9/msam_filter.c:73: undefined reference to `filter_l'
.../Software/msamtools-0.9/msam_filter.c:73: undefined reference to `filter_p'
.../Software/msamtools-0.9/msam_filter.c:73: undefined reference to `filter_lp'
.../Software/msamtools-0.9/msam_filter.c:73: undefined reference to `filter_z'
.../Software/msamtools-0.9/msam_filter.c:73: undefined reference to `filter_lz'
.../Software/msamtools-0.9/msam_filter.c:73: undefined reference to `filter_pz'
.../Software/msamtools-0.9/msam_filter.c:73: undefined reference to `filter_lpz'
collect2: error: ld returned 1 exit status
make[1]: *** [msamtools] Error 1
make[1]: Leaving directory `.../Software/msamtools-0.9'
make: *** [all-recursive] Error 1
```
`./configure` ran without warnings/errors

I've tried with both gcc 5.1.0 and gcc 8.2.0

Hope you can help.

Regards,
Jakob

**Comment by arumugamlab** [comment]
Hi Jakob,

Thanks for reporting this. My gcc is fairly (and embarrassingly) outdated, and still has `-std=gnu89` as default. Newer versions (and yours) are running with `-std=gnu99` as default. This causes an issue (see [here](https://stackoverflow.com/questions/19068705/undefined-reference-when-calling-inline-function)), which I had not tested. To fix this, please rerun **make** with `-std=gnu89`. You might want to delete the currently compiled `*.o` files before that too.

For example:
~~~
rm *.o
make CFLAGS="-std=gnu89 -O2"
~~~

This should compile and make the `msamtools` executable.

I have upgraded the code so that it is now compatible with `-std=gnu99`. The program is now also explicitly built with `-std=gnu99`. This is now pushed to github, but unfortunately cannot be part of the tarball in the 0.9 release. So I updated the installation instructions when using the tarball to include `-std=gnu89` so that it compiles for those with newer gcc versions.

Please let me know if this works.

Best,
Mani

**Comment by Russel88** [comment]
Hi Mani,

It works now. Thank you!

Best,
Jakob
