### ISSUE TITLE
Any convenient script to merge multiple library outputs?

### ISSUE THREAD

**Issue by Anto007** [arumugamlab/msamtools#12]
msamtools is a promising tool for omics analysis. I was wondering if there's a convenient helper script to combine the gene counts in profile outputs for multiple libraries? Thanks!

**Comment by arumugamlab** [comment]
Do you mean merging profile outputs for multiple samples, where each was mapped to the same gene database? Or do you mean merging profile outputs for mapping one sample against multiple databases? Can you please elaborate?

**Comment by Anto007** [comment]
@arumugamlab many thanks for your prompt response. I meant merging profile outputs for multiple samples, where each was mapped to the same gene database. For example, salmon has a function called quantmerge to merge or append together outputs based on specified library names and tpm counts for each sample. The output there is a merged table that contains the gene names in the first column and the tpm counts for the various sample libraries in the subsequent columns.

**Comment by arumugamlab** [comment]
We have an `R` script to combine multiple msamtools outputs in our [MIntO](https://github.com/arumugamlab/MIntO) pipeline. Please check out [merge_profiles.R](https://github.com/arumugamlab/MIntO/blob/main/scripts/merge_profiles.R) that can combine msamtools output files, e.g. `f1.txt.gz`, `f2.txt.gz`, `f3.txt.gz`, using such a command:
```
Rscript merge_profiles.R --keys ID --zeroes --out combined.txt.gz --input f1.txt.gz,f2.txt.gz,f3.txt.gz 
```
**Some notes:**

1. Argument `--keys ID` is needed for msamtools output.

1. The `--input` argument should be a comma-delimited list of input files (gzipped files with `.gz` extension are automatically handled).

1. The output file will be gzipped if `--output` argument has `.gz` extension.

1. It needs the following libraries in R: `optparse`, `R.utils`, `data.table`, `parallel`.

1. It can be multi-threaded using the `--threads` argument - but use it sparingly. Too many threads might actually slow you down since this is a lot of I/O.

1. Use `--zeroes` if you want a compact file where features are skipped when all samples have `0` for that feature.

Please let us know if this works for you. We are happy to support if the script needs any improvement in handling your msamtools output files.

**Comment by Anto007** [comment]
Thank you very much. I'll try this out; closing this ticket for now.
