### ISSUE TITLE
Importance of sorting for pseudo-unpaired data

### ISSUE THREAD

**Issue by shiraz-shah** [arumugamlab/msamtools#5]
Less of an issue, more of a question:
After read qc, a major portion of my reads have had one mate discarded, such that only some of my reads are paired. During assembly such data was supplied in three files: left, right and unpaired. But while mapping, bwa does not support such mixed data, so the mem alignment was done in unpaired mode, concatenating left, right and unpaired files for input.

Thus reads are ordered in the input file so any mates do not follow each other immediately, although they are named identically.

In this case, prior to msamtools filter, would it be better to not to sort by QNAME? Would sorting by qname fool msamtools filter into thinking that mappings for both mates represent a single read, while in fact they are two?

**Comment by arumugamlab** [comment]
**filter** and **profile** programs work differently. While **filter** works read-by-read, **profile** works insert-by-insert. But both work **locally** not **globally** -- meaning they do not have a table of read names that they check against, but just group reads occurring together with the same name. If the same name occurs twice in two different locations, both programs will treat them as two independent reads.

For **filter**, it depends on the exact names used in the fastq file. If the first and second read have the **exact same** name, are mapped in unpaired mode, and put next to each other after QNAME-sorting, then **filter** will have no choice but to treat them as though they are the same. I believe practically every tool will do the same (unless they are checking the SEQ field, which they probably don't). You are better off leaving the output as is without any extra sorting, since most aligners create SAM/BAM files where alignments for a given read are together.

For **profile**, in your case, the behavior is similar to what I said above. If you want the two reads to be counted separately, do not sort by QNAME.

Having said that, my opinion is that paired-end reads should be counted once, not twice, since they are two ends of the same evidence but not two independent pieces of evidence. This is why **profile** is written explicitly with **inserts** in mind. We have dealt with issues like this as a result of QC, and our approach is to align the paired reads in paired mode and align the (combined) unpaired reads in unpaired mode, to combine the two bam files using **samtools merge** and then to pass it on to **msamtools**.

Hope this helps.

**Comment by shiraz-shah** [comment]
Very informative. Thank you, Mani!
